# Generated by Django 5.1.4 on 2024-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20240704_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='State_Medical_Council',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=20),
        ),
    ]
